name: medpad
description: medpad application, medical revolution.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get: ^4.1.4
  get_storage: ^2.0.2
  data_table_2: ^2.0.3
  flutter_custom_clippers: ^2.0.0
  http: any
  shared_preferences: ^2.0.5
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0
  dropdown_search: ^0.6.3
  fl_chart: ^0.36.1
  provider: ^5.0.0
  percent_indicator: "^2.1.7+2"
  datetime_picker_formfield: ^2.0.0
  flutter_spinkit: "^5.0.0"
  rounded_loading_button: ^2.0.3
  double_back_to_close_app: ^2.0.1
  syncfusion_flutter_charts: ^19.2.48
  syncfusion_flutter_pdf: ^19.2.57-beta
  syncfusion_flutter_pdfviewer: ^19.2.57-beta
  avatar_glow: ^1.2.0
  lottie: ^1.1.0
  speech_to_text: ^5.0.0
  pdf: ^3.4.2
  easy_folder_picker: any
  animations: ^2.0.1
  printing: ^5.5.0
  expandable: ^5.0.1
  ota_update: ^3.1.0
  package_info: ^2.0.2
  permission_handler: ^8.1.4+2
  data_connection_checker: ^0.3.4
  steps: ^1.0.1
  image_picker: any
  sqflite: ^1.1.3
  bubble_tab_indicator: "^0.1.5"
  signature: ^4.1.1
  page_transition: any
  flutter_easyloading: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/svg/
    - assets/images/
    - assets/lotties/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
